config/routes.rb
Rails.application.routes.draw do


  post '/rate' => 'rater#create', :as => 'rate'
  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/create'

  get '/', to: 'site#index', as: 'site'

  get '/signup', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  # Edit user routes
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  #Event routes
  get '/events', to: 'event#index', as: 'all_events'
  get '/events/new', to: 'event#new', as: 'new_event'
  get '/events/:id', to: 'event#show', as: 'event'
  get '/events/:id/edit', to: 'event#edit', as: 'edit_event'
  put '/events/:id/edit', to: 'event#update'
  patch '/events/:id/edit', to: 'event#update'
  post '/events', to: 'event#create', as: 'create_event'
  delete '/events/:id', to: 'event#destroy'
  post '/events/:id', to: 'event#add_attender'
  patch '/events/:id', to: 'event#remove_attender'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  # Sale Routes
  get '/sales', to: 'sales#index', as: 'sales'
  get '/sales/new', to: 'sales#new', as: 'new_sale'
  post '/sales', to: 'sales#create', as: 'create_sale'
  get '/sales/:id', to: 'sales#show', as: 'sale'
  post '/sales/:id', to: 'sales#purchase'
  patch '/sales/:id', to: 'sales#confirm'
  get '/sales/:id/edit', to: 'sales#edit', as: 'sale_edit'
  patch '/sales/:id/edit', to: 'sales#update'
  delete '/sales/:id', to: 'sales#destroy'

  # Rent Routes
  get '/rents', to: 'rents#index', as: 'all_rents'
  get '/rents/new', to: 'rents#new', as: 'new_rent'
  get '/rents/:id', to: 'rents#show', as: 'rent'
  get '/rents/:id/edit', to: 'rents#edit', as: 'edit_rent'
  put '/rents/:id/edit', to: 'rents#update'
  patch '/rents/:id/edit', to: 'rents#update'
  post '/rents', to: 'rents#create', as: 'create_rent'
  delete '/rents/:id', to: 'rents#destroy'

  post '/rents/new', to: 'rents#new'


  #Mailbox Routes
  resources :conversations do
    resources :messages
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: User
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: User
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
 where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :jointables, dependent: :destroy
  has_many :users, through: :jointables
  has_many :pictures
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :rent
  has_attached_file :photo, :styles => { :small => "150x150>", :large => "320x240>" }
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
end

app/models/jointable.rb
class Jointable < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :rent
  belongs_to :event
  belongs_to :sale
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/rent.rb
class Rent < ApplicationRecord

  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }

  belongs_to :user
  has_many :pictures
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  has_many :pictures
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :email, presence: true
    validates :email, uniqueness: true

    has_secure_password
    has_many :conversations, foreign_key: :sender_id
    has_many :events, through: :jointables

    has_many :rents, dependent: :destroy
    has_many :sales, dependent: :destroy

    has_many :jointables, dependent: :destroy
    has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: 'http://i.imgur.com/7Yc9GZf.png'
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    ratyrate_rateable 'rating'
    ratyrate_rater

    def self.confirm(params)
        @user = User.find_by(email: params[:email])
        @user ? @user.authenticate(params[:password]) : false
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
      login(@user)
      redirect_to @user
  end

  def show
    @user = User.find_by_id(params[:id])
    @orders = Sale.where({:buyer_id => current_user.id})
    @events = Event.all
    @my_events = Event.where(user_id:current_user.id)
  end


  def edit
    user_id = current_user.id
    @user = User.find_by_id(user_id)
  end

  def update
    user_id = current_user.id
    @user = User.find_by_id(user_id)

    @user.update_attributes(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    delete_user = User.find_by_id(params[:id])
    User.destroy(delete_user)
    redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:email, :avatar, :first_name, :last_name, :password, :city, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_rents.html.erb
<div id="rent">
  <h3>Active Places for rent:</h3>
  <% @user.rents.each do |rent| %>
  <div class="card profile-card">
    <div class="card-block">
      <p><%= link_to rent.title,  rent_path(rent.id) %></p> <br />
          <%= rent.body[0,300]+"..." %>
        <div class="pull-right">
          <%= link_to("Edit", edit_rent_path(rent.id), class: 'btn btn-info btn-xs')%>
          <%= link_to("Delete", rent_path(rent.id), :method => :delete, data: {confirm: "Are you sure you want to delete #{rent.title}?"}, class: 'btn btn-danger btn-xs') %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_sales.html.erb
<div>
<h3>Active Items on Sale:</h3>
<% @user.sales.each do |sale| %>
<div class="card profile-card">
  <div class="card-block">
    <p><%= link_to sale.title,  sale_path(sale.id) %></p> <br />
        <%= sale.body[0,300]+"..." %>
      <div class="pull-right">
        <%= link_to("Edit", sale_edit_path(sale.id), class: 'btn btn-info btn-xs')%>
        <%= link_to("Delete", sale_path(sale.id), :method => :delete, data: {confirm: "Are you sure you want to delete #{sale.title}?"}, class: 'btn btn-danger btn-xs') %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="text-center">
                    <h1>Edit Form</h1>
                </div>
            </div>
            <%= form_for @user do |f| %>
            <form>
                <fieldset class="form-group">
                    <label for="current_city">First Name</label>
                    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
                </fieldset>

                <fieldset class="form-group">
                    <label for="profile_image">Last Name</label>
                    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
                </fieldset>

                <fieldset class="form-group">
                    <label for="profile_image">City</label>
                    <%= f.text_field :city, class: "form-control", placeholder: "City" %>
                </fieldset>
                <%= f.file_field :avatar %>

                <fieldset class="form-group">
                    <%= f.submit "Save", class: "btn btn-primary" %>
                </fieldset>
            </form>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<h1>Welcome to Users Index.</h1>

<div>
There are currently <%= @users.length %> user(s) signed up!
</div>

app/views/users/new.html.erb
Sign Up

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :city, placeholder: "City" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
    <%= f.file_field :avatar %>
  </div>
  <div>
    <%= f.hidden_field :rating, :value => 5 %>
    <%= f.hidden_field :balance, :value => 1000 %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
    <div class="row">

        <div class="col-md-3">

            <h3>Welcome,
                <%= @user.first_name%>!</h3>
            <br>
            <%= image_tag(@user.avatar.url, :class => 'profile-picture') %>
            <br><%= @user.first_name%>
            is attending:
            <%@joins = Jointable.where(user_id:@user.id)%>
            <%@joins.each do |join| %>
            <br>
            <%@attending = Event.find_by_id(join.event_id)%>

            Event:
            <%= @attending.title%>
            <br>
            Date:
            <%= @attending.date%>
            <%end%>
            <br>
            Seller Rating:
            <%= rating_for @user, 'rating', star: @user.rating %>
            <br/>
            <% if current_user == @user%>
            <%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %>
            <%= link_to("Delete", user_path, :method => :delete, data: {confirm: "Are you sure you want to delete your account?"}, class: 'btn btn-danger') %>
            <%end%>
            <hr/>
            <%= link_to("New Sale", new_sale_path, class: 'btn btn-info') %>
            <br/>
            <%= link_to("New Rent", new_rent_path, class: 'btn btn-info') %>
            <br/>
            <%= link_to("New Event", new_event_path, class: 'btn btn-info') %>
        </div>
      <div id="profile-view" class="col-md-9">
        <div id="event">
          <h3>Active Events:</h3>

          <% @my_events.each do |event| %>
          <div class="card profile-card">
              <p><%= link_to event.title,  event_path(event.id) %></p> <br />
              <%= event.date %><br>
                  <%= event.body[0,300]+"..." %>
                  <div class="pull-right">
                  <% if current_user.id == event.user_id%>
                  <%= link_to("Edit", edit_event_path(event.id), class: 'btn btn-info btn-xs')%>
                  <%= link_to("Delete", event_path(event.id), :method => :delete, data: {confirm: "Are you sure you want to delete #{event.title}?"}, class: 'btn btn-danger btn-xs') %>
                  <%else%>
                    <p>Created By: <%=User.find(event.user_id).first_name%> <%=User.find(event.user_id).last_name%></p>
                  <%end%>
                </div>

            </div>
          <% end %>
        </div>

        <div id="profile-view" >
            <%= render 'sales' %>
            <%= render 'rents' %>
        </div>

    </div>
</div>




</div>
<hr>
</div>
<hr>