config/routes.rb
Rails.application.routes.draw do


  post '/rate' => 'rater#create', :as => 'rate'
  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/create'

  get '/', to: 'site#index', as: 'site'

  get '/signup', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  # Edit user routes
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  #Event routes
  get '/events', to: 'event#index', as: 'all_events'
  get '/events/new', to: 'event#new', as: 'new_event'
  get '/events/:id', to: 'event#show', as: 'event'
  get '/events/:id/edit', to: 'event#edit', as: 'edit_event'
  put '/events/:id/edit', to: 'event#update'
  patch '/events/:id/edit', to: 'event#update'
  post '/events', to: 'event#create', as: 'create_event'
  delete '/events/:id', to: 'event#destroy'
  post '/events/:id', to: 'event#add_attender'
  patch '/events/:id', to: 'event#remove_attender'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  # Sale Routes
  get '/sales', to: 'sales#index', as: 'sales'
  get '/sales/new', to: 'sales#new', as: 'new_sale'
  post '/sales', to: 'sales#create', as: 'create_sale'
  get '/sales/:id', to: 'sales#show', as: 'sale'
  post '/sales/:id', to: 'sales#purchase'
  patch '/sales/:id', to: 'sales#confirm'
  get '/sales/:id/edit', to: 'sales#edit', as: 'sale_edit'
  patch '/sales/:id/edit', to: 'sales#update'
  delete '/sales/:id', to: 'sales#destroy'

  # Rent Routes
  get '/rents', to: 'rents#index', as: 'all_rents'
  get '/rents/new', to: 'rents#new', as: 'new_rent'
  get '/rents/:id', to: 'rents#show', as: 'rent'
  get '/rents/:id/edit', to: 'rents#edit', as: 'edit_rent'
  put '/rents/:id/edit', to: 'rents#update'
  patch '/rents/:id/edit', to: 'rents#update'
  post '/rents', to: 'rents#create', as: 'create_rent'
  delete '/rents/:id', to: 'rents#destroy'

  post '/rents/new', to: 'rents#new'


  #Mailbox Routes
  resources :conversations do
    resources :messages
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: User
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: User
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
 where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :jointables, dependent: :destroy
  has_many :users, through: :jointables
  has_many :pictures
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :rent
  has_attached_file :photo, :styles => { :small => "150x150>", :large => "320x240>" }
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
end

app/models/jointable.rb
class Jointable < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :rent
  belongs_to :event
  belongs_to :sale
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/rent.rb
class Rent < ApplicationRecord

  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }

  belongs_to :user
  has_many :pictures
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  has_many :pictures
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :email, presence: true
    validates :email, uniqueness: true

    has_secure_password
    has_many :conversations, foreign_key: :sender_id
    has_many :events, through: :jointables

    has_many :rents, dependent: :destroy
    has_many :sales, dependent: :destroy

    has_many :jointables, dependent: :destroy
    has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: 'http://i.imgur.com/7Yc9GZf.png'
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    ratyrate_rateable 'rating'
    ratyrate_rater

    def self.confirm(params)
        @user = User.find_by(email: params[:email])
        @user ? @user.authenticate(params[:password]) : false
    end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def index
    if params[:category]
      @rents = Rent.where(:category => params[:category])
    else
      @rents = Rent.all
    end
  end

  def new
      @rent = Rent.new
      @image = Image.new
      2.times {@rent.images.build}
  end

  def create
      @rent = Rent.create(rent_params)
      if @rent.save
        redirect_to @rent
      else
        render :action => 'new'
      end
  end

  def show
      @rent = Rent.find_by_id(params[:id])
  end

  def edit
      @rent = Rent.find_by_id(params[:id])
  end

  def update
      updated_rent = Rent.find_by_id(params[:id])
      if updated_rent.update(rent_params)
          redirect_to user_path(current_user)
      else
          redirect_to edit_rent_path
      end
  end

  def destroy
      deleted_rent = Rent.find_by_id(params[:id])
      Rent.destroy(deleted_rent)
      redirect_to user_path(current_user)
  end

  def contact

  end

  private

  def rent_params
      params.require(:rent).permit(:title, :body, :category, :price, :address, :sqfootage, :bed, :bath, :user_id, :images_attributes=>[:caption, :photo])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rents/edit.html.erb
<h2>Welcome to edit Rent page</h2>

<%= form_for :rent, :method => :put do |f| %>
    <fieldset class="form-group">
      <label for="name">Title</label>
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="email">Descpription</label>
      <%= f.text_area :body, class: "form-control", placeholder: "Descpription" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Category</label>
      <%= f.select :category, ["apartment", "house", "Other" ], class: "form-control", placeholder: "Category" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Price</label>
      <%= f.number_field :price, :step => 0.01 , class: "form-control", placeholder: "Price" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Square Footage</label>
      <%= f.number_field :sqfootage, class: "form-control", placeholder: "Square Footage" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Bedroom</label>
      <%= f.number_field :bed, class: "form-control", placeholder: "Bedroom" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Bathroom</label>
      <%= f.number_field :bath, class: "form-control", placeholder: "Bathroom" %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.hidden_field :user_id, class: "form-control", :value => current_user.id %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.submit "Save", class: "btn btn-primary" %>
      <%= link_to "Cancel", user_path(current_user), class: "btn btn-primary" %>
    </fieldset>
<% end %>

app/views/rents/index.html.erb
<h2><%= link_to "Create Rent Post", new_rent_path, class: "btn btn-success create-post" %></h2>
<br/>
<h3>Filters</h3>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6 filters">

                <%= link_to "Apartment", all_rents_path(:category=>"Apartment"), class: "btn btn-primary" %>
                <%= link_to "House", all_rents_path(:category=>"House"), class: "btn btn-primary" %>
                <%= link_to "Other", all_rents_path(:category=>"Other"), class: "btn btn-primary" %>
                <%= link_to "Undo Filter", all_rents_path, class: "btn btn-default" %>
            </div>
        </div>
        <br/>
        <!-- Card Show -->
        <div class="row">
            <div class="col-md-12">
                <% @rents.each do |rent| %>
                <div class="col-xs-6 col-md-4">
                    <div class="card" style="width: 30rem;">
                        <img class="card-img-top" src="http://www.lily-bearing.com/wp-content/themes/theme/front/dist/images/default.png" alt="Card image cap">
                        <div class="card-block">
                            <h4 class="card-title"><%= rent.title %></h4>
                            <p class="card-text"><strong><%= rent.bed %></strong> Bed/<strong><%=rent.bath%></strong> Bath</p>
                            <p class="card-text"><%= truncate(rent.body, length: 80) %></p>
                            <%= link_to "View", rent_path(rent), class: 'btn btn-info' %>
                            <h3 class="price"><%= number_to_currency(rent.price) %></h3>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>

</div>

app/views/rents/new.html.erb
<h2>Welcome to new Rent page</h2>


<%= form_for @rent, url: create_rent_path, :html => {:multipart => true} do |f| %>

    <fieldset class="form-group">
      <label for="name">Title</label>
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="email">Descpription</label>
      <%= f.text_area :body, class: "form-control", placeholder: "Descpription" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Category</label>
      <%= f.select :category, ["Apartment", "House", "Other" ], class: "form-control", placeholder: "Category" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Price</label>
      <%= f.number_field :price, :step => 0.01 , class: "form-control", placeholder: "Price" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Square Footage</label>
      <%= f.number_field :sqfootage, class: "form-control", placeholder: "Square Footage" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Bedroom</label>
      <%= f.number_field :bed, class: "form-control", placeholder: "Bedroom" %>
    </fieldset>
    <fieldset class="form-group">
      <label for="name">Bathroom</label>
      <%= f.number_field :bath, class: "form-control", placeholder: "Bathroom" %>
    </fieldset>

    <fieldset class="form-group">
      <label for="name">Address</label>
      <%= f.number_field :address, class: "form-control", placeholder: "Address" %>
    </fieldset>

    <fieldset class="form-group">
      <label for="name">Zipcode</label>
      <%= f.number_field :zipcode, class: "form-control", placeholder: "Zipcode" %>
    </fieldset>

    <%= f.fields_for :images do |builder| %>
      <p>
        <%= builder.label :caption, "Image Caption" %>
        <%= builder.text_field :caption %>
      </p>
      <p>
        <%= builder.label :photo, "Image File" %>
        <%= builder.file_field :photo %>
      </p>
    <% end %>


    <fieldset class="form-group">
      <%= f.hidden_field :user_id, class: "form-control", :value => current_user.id %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.submit "Save", class: "btn btn-primary" %>
      <%= link_to "Cancel", all_rents_path, class: "btn btn-primary" %>
    </fieldset>
<% end %>

app/views/rents/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <!-- Category filters -->
      <%= link_to "Back", all_rents_path, class: "btn btn-primary" %>
      <!-- Need to change once messaging is implemented -->
      <%= link_to "Contact landlord",conversations_path(sender_id: current_user.id, recipient_id: Rent.find_by_id(params[:id]).user_id), :method => :post, class: "btn btn-success" %>

    </div>
  </div>
  <div style='width: 800px;'>
      <div id="map" style='width: 800px; height: 400px;'></div>
  </div>
  <div class="row sale-body">
    <div class="col-md-12">
      <h1><strong><%= @rent.title %></strong> - <em>  Location: (<%= @rent.address %>)</em></h1>
            <!-- NOTE: Add loop to generate all images associated with the post -->
            <img class="sale-img" src="http://www.lily-bearing.com/wp-content/themes/theme/front/dist/images/default.png" />
            <img class="sale-img" src="http://www.lily-bearing.com/wp-content/themes/theme/front/dist/images/default.png" />
            <img class="sale-img" src="http://www.lily-bearing.com/wp-content/themes/theme/front/dist/images/default.png" />
            <img class="sale-img" src="http://www.lily-bearing.com/wp-content/themes/theme/front/dist/images/default.png" />
            <h3><strong>Asking Price:</strong> <%= number_to_currency(@rent.price) %></h3>
            <h4><%= @rent.body %></h4>
    </div>
  </div>
</div>
<script type="text/javascript">

    handler = Gmaps.build('Google');
    var places = [];

    $.ajax({
        method: "GET",
        url: "https://api.geocod.io/v1/geocode?q=<%=@rent.zipcode%>&api_key=d7ae4d877f80d76b705fef40487e7519d985079",
        dataType: "json",
        async: false,
        success: function (data) {
            places.push({"lat": data.results[0].location.lat, "lng": data.results[0].location.lng, "infowindow": "#{@rent.title}"});
        }
    });
    function initialize() {
        var miles = 3;

        var map = new google.maps.Map(document.getElementById("map"), {
            zoom: 11,
            center: new google.maps.LatLng(places[0].lat, places[0].lng),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        var circle = new google.maps.Circle({
            center: new google.maps.LatLng(places[0].lat, places[0].lng),
            radius: miles * 1609.344,
            fillColor: "#ff69b4",
            fillOpacity: 0.5,
            strokeOpacity: 0.0,
            strokeWeight: 0,
            map: map
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);


$(document).ready(function(){
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL+"#";
        location = "#";

        //Reload the page
        location.reload(true);
    }
});
</script>