config/routes.rb
Rails.application.routes.draw do


  post '/rate' => 'rater#create', :as => 'rate'
  get 'messages/index'

  get 'messages/new'

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/create'

  get '/', to: 'site#index', as: 'site'

  get '/signup', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  # Edit user routes
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  #Event routes
  get '/events', to: 'event#index', as: 'all_events'
  get '/events/new', to: 'event#new', as: 'new_event'
  get '/events/:id', to: 'event#show', as: 'event'
  get '/events/:id/edit', to: 'event#edit', as: 'edit_event'
  put '/events/:id/edit', to: 'event#update'
  patch '/events/:id/edit', to: 'event#update'
  post '/events', to: 'event#create', as: 'create_event'
  delete '/events/:id', to: 'event#destroy'
  post '/events/:id', to: 'event#add_attender'
  patch '/events/:id', to: 'event#remove_attender'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  # Sale Routes
  get '/sales', to: 'sales#index', as: 'sales'
  get '/sales/new', to: 'sales#new', as: 'new_sale'
  post '/sales', to: 'sales#create', as: 'create_sale'
  get '/sales/:id', to: 'sales#show', as: 'sale'
  post '/sales/:id', to: 'sales#purchase'
  patch '/sales/:id', to: 'sales#confirm'
  get '/sales/:id/edit', to: 'sales#edit', as: 'sale_edit'
  patch '/sales/:id/edit', to: 'sales#update'
  delete '/sales/:id', to: 'sales#destroy'

  # Rent Routes
  get '/rents', to: 'rents#index', as: 'all_rents'
  get '/rents/new', to: 'rents#new', as: 'new_rent'
  get '/rents/:id', to: 'rents#show', as: 'rent'
  get '/rents/:id/edit', to: 'rents#edit', as: 'edit_rent'
  put '/rents/:id/edit', to: 'rents#update'
  patch '/rents/:id/edit', to: 'rents#update'
  post '/rents', to: 'rents#create', as: 'create_rent'
  delete '/rents/:id', to: 'rents#destroy'

  post '/rents/new', to: 'rents#new'


  #Mailbox Routes
  resources :conversations do
    resources :messages
  end


end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: User
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: User
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
 where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :jointables, dependent: :destroy
  has_many :users, through: :jointables
  has_many :pictures
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :rent
  has_attached_file :photo, :styles => { :small => "150x150>", :large => "320x240>" }
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
end

app/models/jointable.rb
class Jointable < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :rent
  belongs_to :event
  belongs_to :sale
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/rent.rb
class Rent < ApplicationRecord

  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }

  belongs_to :user
  has_many :pictures
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  has_many :pictures
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :email, presence: true
    validates :email, uniqueness: true

    has_secure_password
    has_many :conversations, foreign_key: :sender_id
    has_many :events, through: :jointables

    has_many :rents, dependent: :destroy
    has_many :sales, dependent: :destroy

    has_many :jointables, dependent: :destroy
    has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: 'http://i.imgur.com/7Yc9GZf.png'
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    ratyrate_rateable 'rating'
    ratyrate_rater

    def self.confirm(params)
        @user = User.find_by(email: params[:email])
        @user ? @user.authenticate(params[:password]) : false
    end
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Dlist</title>

        <%= csrf_meta_tags %>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="//maps.google.com/maps/api/js?key=AIzaSyD5mXf1-SkLEADM4CylGjeo7KtVZeipKoc"></script>
        <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
        <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="head-nav">
            <% if current_user%>
            Balance:
            <%=number_to_currency(current_user.balance)%>
            |
            <%= link_to "Mailbox", conversations_path %>
            |
            <%= link_to "Contact Us", conversations_path(sender_id: current_user.id, recipient_id: User.find_by_email("admin@dlist.com").id), :method => :post%>
            |
            <%= link_to "Profile", user_path(current_user) %>
            |
            <%= link_to "Log Out", logout_path %>
            |
        <% else %>
            <%= link_to "Create Account", new_user_path %>
            |
            <%= link_to "Log In", login_path %>
            |
            <% end %>
            <%= link_to "Home", site_path %>
        </div>

        <% flash.each do |name, msg| %>
        <p>
            <small>
                <%= name.capitalize %>:
                <%= msg %>
            </small>
        </p>
        <% end %>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <%= yield %>
                </div>
            </div>
        </div>

    </body>

</html>